bash scripts/California_ISO/itrans_m.sh
bash scripts/California_ISO/patchTST_m.sh
bash scripts/Germany_Renewable_Power_Grid/itrans_m.sh
bash scripts/Germany_Renewable_Power_Grid/patchTST_m.sh
bash scripts/Jena_Atmospheric_Physics/itrans_m.sh
bash scripts/Jena_Atmospheric_Physics/patchTST_m.sh
bash scripts/NYC_traffic_speed/itrans_m.sh
bash scripts/NYC_traffic_speed/patchTST_m.sh
bash scripts/Bear_room/itrans_m.sh
bash scripts/Bear_room/patchTST_m.sh